apiVersion: apps/v1
kind: Deployment
metadata:
  name: atls-backend
spec:
  selector:
    matchLabels:
      app: atls.app
  replicas: 3
  template:
    metadata:
      labels:
        app: atls.app
    spec:
      volumes:
      - name: shared-data
        emptyDir: {}
      containers:
      - name: nginx
        image: nginx:latest
        volumeMounts:
        - name: shared-data
          mountPath: /usr/share/nginx/html
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: atls-lb
spec:
  selector:
    app: atls.app
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      name: http
